[package]
name = "fil_actor_multisig"
description = "Builtin multisig actor for Filecoin"
version = "8.0.0-alpha.1"
license = "MIT OR Apache-2.0"
authors = ["ChainSafe Systems <info@chainsafe.io>", "Protocol Labs", "Filecoin Core Devs"]
edition = "2018"
repository = "https://github.com/filecoin-project/builtin-actors"
keywords = ["filecoin", "web3", "wasm"]

[lib]
## lib is necessary for integration tests
## cdylib is necessary for Wasm build
crate-type = ["cdylib", "lib"]

[dependencies]
fil_actors_runtime = { version = "8.0.0-alpha.1", path = "../runtime" }
fvm_shared = { version = "0.3.1", default-features = false }
fvm_ipld_hamt = "0.3.0"
num-traits = "0.2.14"
num-derive = "0.3.3"
cid = { version = "0.8.3", default-features = false, features = ["serde-codec"] }
indexmap = { version = "1.8.0", features = ["serde-1"] }
integer-encoding = { version = "3.0.3", default-features = false }
serde = { version = "1.0.136", features = ["derive"] }
anyhow = "1.0.56"

[dev-dependencies]
fil_actors_runtime = { version = "8.0.0-alpha.1", path = "../runtime", features = ["test_utils", "sector-default"] }
