[package]
name = "filecoin_canonical_actors_bundle"
description = "Bundle containing Filecoin canonical actors"
version = "0.1.0"
license = "MIT OR Apache-2.0"
edition = "2021"
repository = "https://github.com/filecoin-project/canonical-actors"

[dependencies]
clap = { version= "3.0.14", features = ["derive"] }
fvm_shared = { path = "../../fvm/shared" }
ipld_car = { path = "../../fvm/ipld/car" }
cid = { version = "0.8.2", default-features = false, features = ["serde-codec"] }
multihash = { version = "0.16.1", default-features = false, features = ["identity"] }
async-std = { version = "1.10.0" }
futures = "0.3.21"
fil_actor_bundler = { path = "./bundler" }

[build-dependencies]
fil_actor_bundler = { path = "./bundler" }
cid = { version = "0.8.2", default-features = false, features = ["serde-codec"] }